//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEW.ApplicationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EAStats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EAStats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEW.ApplicationResources.EAStats", typeof(EAStats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta.
        /// </summary>
        public static string ButtonFetch {
            get {
                return ResourceManager.GetString("ButtonFetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skriv in ditt EA:Id i fältet för att hämta din statistik för NHL 10..
        /// </summary>
        public static string FetchStatsTooltip {
            get {
                return ResourceManager.GetString("FetchStatsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jämför.
        /// </summary>
        public static string LabelCompare {
            get {
                return ResourceManager.GetString("LabelCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stekhet eller Iskall?.
        /// </summary>
        public static string LabelCurrentShape {
            get {
                return ResourceManager.GetString("LabelCurrentShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuvarnade Vinstsvit.
        /// </summary>
        public static string LabelCurrentStreak {
            get {
                return ResourceManager.GetString("LabelCurrentStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagram.
        /// </summary>
        public static string LabelDiagram {
            get {
                return ResourceManager.GetString("LabelDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA NHL - Statistik.
        /// </summary>
        public static string LabelEAStats {
            get {
                return ResourceManager.GetString("LabelEAStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämtat från EA.
        /// </summary>
        public static string LabelFetchedDate {
            get {
                return ResourceManager.GetString("LabelFetchedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spel.
        /// </summary>
        public static string LabelGame {
            get {
                return ResourceManager.GetString("LabelGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelade Matcher.
        /// </summary>
        public static string LabelGamesPlayed {
            get {
                return ResourceManager.GetString("LabelGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allmänt.
        /// </summary>
        public static string LabelGeneralStatsSubHeader {
            get {
                return ResourceManager.GetString("LabelGeneralStatsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förluster.
        /// </summary>
        public static string LabelLosses {
            get {
                return ResourceManager.GetString("LabelLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Övertidsförluster.
        /// </summary>
        public static string LabelOvertimeLosses {
            get {
                return ResourceManager.GetString("LabelOvertimeLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avklarade numerära underlägen.
        /// </summary>
        public static string LabelPenaltyKillPercent {
            get {
                return ResourceManager.GetString("LabelPenaltyKillPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerärt underläge.
        /// </summary>
        public static string LabelPenaltyStatsSubHeader {
            get {
                return ResourceManager.GetString("LabelPenaltyStatsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        public static string LabelPlatform {
            get {
                return ResourceManager.GetString("LabelPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insläppta mål i numerärt överläge.
        /// </summary>
        public static string LabelPowerPlayGoalsAgainst {
            get {
                return ResourceManager.GetString("LabelPowerPlayGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjorda mål i numerärt överläge.
        /// </summary>
        public static string LabelPowerPlayGoalsFor {
            get {
                return ResourceManager.GetString("LabelPowerPlayGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal numerära överlägen.
        /// </summary>
        public static string LabelPowerPlayOpportunities {
            get {
                return ResourceManager.GetString("LabelPowerPlayOpportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lyckade numerära överlägen.
        /// </summary>
        public static string LabelPowerPlayPercent {
            get {
                return ResourceManager.GetString("LabelPowerPlayPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerärt överläge.
        /// </summary>
        public static string LabelPowerPlayStatsSubHeader {
            get {
                return ResourceManager.GetString("LabelPowerPlayStatsSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSN-Id.
        /// </summary>
        public static string LabelPSNId {
            get {
                return ResourceManager.GetString("LabelPSNId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insläppta mål i numerärt underläge.
        /// </summary>
        public static string LabelShortHandedGoalsAgainst {
            get {
                return ResourceManager.GetString("LabelShortHandedGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjorda mål i numrärt underläge.
        /// </summary>
        public static string LabelShortHandedGoalsFor {
            get {
                return ResourceManager.GetString("LabelShortHandedGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchhistorik.
        /// </summary>
        public static string LabelShowHistory {
            get {
                return ResourceManager.GetString("LabelShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Statistik.
        /// </summary>
        public static string LabelShowStats {
            get {
                return ResourceManager.GetString("LabelShowStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal numerära underlägen.
        /// </summary>
        public static string LabelTimesShortHanded {
            get {
                return ResourceManager.GetString("LabelTimesShortHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EA-poäng.
        /// </summary>
        public static string LabelTotalPoints {
            get {
                return ResourceManager.GetString("LabelTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .vs.
        /// </summary>
        public static string LabelVersus {
            get {
                return ResourceManager.GetString("LabelVersus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinster.
        /// </summary>
        public static string LabelWins {
            get {
                return ResourceManager.GetString("LabelWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senaste {0} matcherna.
        /// </summary>
        public static string LatestGames {
            get {
                return ResourceManager.GetString("LatestGames", resourceCulture);
            }
        }
    }
}
